### ISSUE TITLE
下载完分辨率都是720P

### ISSUE THREAD

**Issue by wuwao1** [JelinYao/BVLoader#3]
<img width="353" alt="image" src="https://user-images.githubusercontent.com/29857592/194534748-7356c812-75d1-455b-92d7-00706be0fa3c.png">

**Comment by JelinYao** [comment]
![image](https://user-images.githubusercontent.com/7205249/197436418-f2b82f1d-beee-4afa-be3c-6c99e806193c.png)
是不是没有登录，B站账号登陆才能下载1080P及以上分辨率的，这是B站的限制。
